services:
  - type: web
    name: zeins-help-center-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://zeins-web-setup.web.app
      - key: JWT_SECRET
        generateValue: true
      - key: FIREBASE_STORAGE_BUCKET
        value: zeins-web-setup.firebasestorage.app
      - key: CLOUDINARY_CLOUD_NAME
        value: dneatk4ks
      - key: CLOUDINARY_API_KEY
        value: "126185716818649"
      - key: CLOUDINARY_API_SECRET
        value: cqHijga8P0ZCt4P8nB_L9jGpVPM
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
